### ISSUE TITLE
Not seeing logs in Loki

### ISSUE THREAD

**Issue by nreddipalle** [corentinaltepe/nlog.loki#37]
Hello @corentinaltepe  this is my NLog.config.. 
I am seeing logs on local log file application-logs.json but nothing in loki when searching with label app.
Please let me know if anything is wrong with config...

Loki is behind ingress so did not add port to the URL.. did a test CURL with sample json to below endpoint and it is posted fine..

Loki version is: grafana/loki:2.3.0
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<!--
  See https://github.com/nlog/nlog/wiki/Configuration-file
  for information on customizing logging rules and outputs.
   -->
	<extensions>
		<add assembly="Genome.Utility"/>
		<add assembly="NLog.DiagnosticSource" />
		<add assembly="NLog.Loki" />
	</extensions>
	<targets async="true">
		<!-- Write logs as Json into a file -->
		<target name="json-file" xsi:type="File" fileName="application-logs.json">
			<layout xsi:type="JsonLayout" includeMdlc="true">
				<attribute name="date" layout="${date:format=yyyy-MM-ddTHH\:mm\:ss.fff}" />
				<attribute name="level" layout="${level:upperCase=true}"/>
				<attribute name="message" layout="${message}|ActivityId=${activity:property=TraceId}|TraceId=${activity:property=TraceId}|SpanId =${activity:property=SpanId}" />
				<attribute name="exception" layout="${exception:format=ToString}" />
			</layout>
		</target>
		<target
		  name="loki"
		  xsi:type="loki"
		  batchSize="2"
		  taskDelayMilliseconds="500"
		  endpoint="https://LOKI_ENDPOINTURL/loki/api/v1/push"
		  username="USERNAME"
		  password="PASSWORD"
		  orderWrites="true"
		  compressionLevel="noCompression"
		  layout="${level}|${message}${onexception:|${exception:format=type,message,method:maxInnerExceptionLevel=5:innerFormat=shortType,message,method}}|source=${logger}">

			<label name="app" layout="newapp-dev" />
			<label name="server" layout="${hostname:lowercase=true}" />
		</target>
		<target name="diagSource" xsi:type="diagnosticListener" layout="${message}|TraceId=${activity:property=TraceId}" sourceName="nlog" eventName="${logger}" />
	</targets>
	<rules>
		<!-- Log all events to the json-file target -->
		<logger name="*" writeTo="json-file" minlevel="Trace" />
		<logger name="*" writeTo="diagSource" minlevel="Trace" />
		<logger name="*" minlevel="Trace" writeTo="loki" />
	</rules>
</nlog>
```

**Comment by corentinaltepe** [comment]
Hello @nreddipalle. Can you try to set the endpoint as follows and let me know if this solves your problem?

`endpoint="https://LOKI_ENDPOINTURL"` 

This is because the target already adds the `/loki/api/v1/push` to the URL, so you don't have to. See [source here](https://github.com/corentinaltepe/nlog.loki/blob/110fda0a58da3776e9237839ef29d1fd2829ff5e/src/NLog.Loki/HttpLokiTransport.cs#L36).

**Comment by nreddipalle** [comment]
Thank you.. I did not see in Loki still even if I see in my local log file.. let me enable internal logging and post my findings.

**Comment by nreddipalle** [comment]
@corentinaltepe Seeing this error in logs..

```
2022-05-26 16:44:27.9384 Warn loki: WriteAsyncTask failed on completion. Sleep 500 ms Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NLog.Loki.HttpLokiTransport.<WriteLogEventsAsync>d__4.MoveNext()

```

my loki is in AKS behind ngnix ingress.. fyi

**Comment by corentinaltepe** [comment]
Sorry but I don't really know why we have `System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.`.

Could you post the curl command which successfully sends logs to Loki (replace your basic auth header value and parts of the URL with `****`)? Please run it with `-v` option to get some details about the request, especially the TLS version used.

Is the behavior the same if you specify the HTTPS port to 443 like so? `endpoint="https://LOKI_ENDPOINTURL:443"`


A quick search with the error would point towards incompatible TLS version used between the client and server, I'm not entirely sure. The target doesn't offer configuration to set the TLS version used, so I guess it uses the .NET runtime's default. Which version of the .NET is your app running on? Can [this documentation](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls) help?

> Consider the following recommendations:
> - For TLS 1.2, target .NET Framework 4.7 or later versions on your apps, and target .NET Framework 4.7.1 or later versions on your WCF apps.
> - For TLS 1.3, target .NET Framework 4.8 or later.
> - Do not specify the TLS version. Configure your code to let the OS decide on the TLS version.
> - Perform a thorough code audit to verify you're not specifying a TLS or SSL version.
>
> When your app lets the OS choose the TLS version:
> - It automatically takes advantage of new protocols added in the future, such as TLS 1.3.
> - The OS blocks protocols that are discovered not to be secure.

**Comment by nreddipalle** [comment]
Its good now when testing from AKS pod itself. closing..

**Comment by nreddipalle** [comment]
@corentinaltepe One final question, I want to make some fields configurable and read via appsettings.config (.NET framework app) like LogInfo and Enabled fields under Rules..

I assume this is allowed..

```
<label name="customer" layout="${appsetting:item=customercode:default=sensei}" />
<label name="environment" layout="${appsetting:item=environment:default=dev}" />
```
can you please confirm if this is possible

```
<variable name="AppLogLevel" value="${appsetting:item=LogLevel:default=Trace}" />
<variable name="NLogEnabled" value="${appsetting:item=NLogEnabled:default=false}" />

Instead of this
<rules>
<logger name="*" minlevel="Trace" writeTo="loki" enabled="true" />
</rules>

need something like this

<rules>
<logger name="*" minlevel="${AppLogLevel}" writeTo="loki" enabled="${NLogEnabled}" />
</rules>
```
Let me know if it is possible or what is the best way to setup LogLevel and enable/disable NLog via appsettings.config.
Thanks.
