### ISSUE TITLE
Add gRPC client implementation

### ISSUE THREAD

**Issue by corentinaltepe** [corentinaltepe/nlog.loki#4]

**Comment by corentinaltepe** [comment]
I think a gRPC implementation should be part of a separate library entirely.

**Comment by corentinaltepe** [comment]
Implemented in a separate project, see: https://github.com/corentinaltepe/nlog.loki.grpc

**Comment by snakefoot** [comment]
Notice if you are interested in benchmarking HTTP vs GRPC. Then notice that NLog v5.2.5 has updated the SpinCount for concurrent-queue-handling: https://www.nuget.org/packages/NLog#releasenotes-body-tab

This had major improvement on benchmark results, when using OverflowAction=Block. This will also affects targets that inherits from AsyncTaskTarget.
