### ISSUE TITLE
[Feature Request] optional proxy settings

### ISSUE THREAD

**Issue by erSitzt** [corentinaltepe/nlog.loki#41]
Hi,

as HttpClient is used for Loki it would be nice to add proxy support as many corporate networks still rely on proxies.

These two support proxies
https://github.com/AlanBarber/NLog.Targets.Splunk
https://github.com/DarekDan/NLog.Targets.HTTP

**Comment by corentinaltepe** [comment]
Hello @erSitzt, thank you for your proposal.

Given HttpClient supports proxy, [see documentation here](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0#proxies), that's be great to pass proxy configuration to the client.

We'd likely need two or three properties, right?
- credentials, I imagine user password or a token
- url

Would you feel like submitting a PR to add that feature?

**Comment by erSitzt** [comment]
@corentinaltepe I'm more of a "hobbyist" c# guy :) if i find the time i can try.. but it might need some refurbishment afterwards ;)

**Comment by corentinaltepe** [comment]
Hi @erSitzt, over a year later but the feature is available starting v1.5.0.
