### ISSUE TITLE
Authentication support

### ISSUE THREAD

**Issue by scattered-code** [corentinaltepe/nlog.loki#5]
I'm trying to send logs to a loki instance hosted by grafana.net, and they use basic authentication. I'll submit a PR shortly since I got it working, but feel free to suggest a different way.

**Comment by corentinaltepe** [comment]
That'd be great! I will be on a break for the next two weeks, I won't be able to run the code. But I can read PRs, merge them and publish a new package version. Will do my best to help this way.

**Comment by corentinaltepe** [comment]
I've just pushed a [v1.0.9](https://www.nuget.org/packages/CorentinAltepe.NLog.Loki/1.0.9) with your PR. It should be listed soon. Thank you very much!
