### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by A6blpka** [corentinaltepe/nlog.loki#50]
@corentinaltepe, can you add [strong name](https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named) to the library like [this one](https://github.com/NLog/NLog.DiagnosticSource/pull/13/files).
Without this feature, I use your library as a reference in my strongly named library and then can't use my library in a .net framework app.

**Comment by corentinaltepe** [comment]
Hi @A6blpka, I see no reason not to strongly name the assembly, if it can benefit NET Framework libraries and apps. I'll see if I can do this soon, or you'd be welcome to submit a PR and I'll publish a new version. Thank you.
