### ISSUE TITLE
Resiliency support

### ISSUE THREAD

**Issue by scattered-code** [corentinaltepe/nlog.loki#6]
Hi,
I noticed that WriteLogEventsAsync just does a fire and forget on the HTTP request. Is there a performance reason for it?
I suggest adding https://github.com/App-vNext/Polly with a retry, circuit breaker and timeout policy, and calling EnsureSuccessStatusCode() on the POST

**Comment by corentinaltepe** [comment]
Actually, I think it should do something like that at the very minimum:

```cs
var response = await client.PostAsync(...);
response.EnsureSuccess();
```

This way, the code throws if it fails, and then NLog logs internally the response. I believe NLog supports retry mechanism with async targets, such that we don't have to use polly and do it ourselves. But I should dig into NLog's doc to make sure of it.

If we want more detail logs of why the request failed, we should try to read the response content in case of failure and log it to NLogs' internal logs.

**Comment by corentinaltepe** [comment]
Also
`Is there a performance reason for it?`. No. I just forked from [this repo](https://github.com/anton-gogolev/nlog.loki), which seemed not maintained anymore and its nuget package had been unlisted. So your contribution is very welcome.
