### ISSUE TITLE
Not work when run in Ubuntu

### ISSUE THREAD

**Issue by msyzzm** [corentinaltepe/nlog.loki#67]
I am working with loki and grafana in grafana.com. I write some test code to log and build it. When I run the build in Windows it works fine, but when I run it in Ubuntu, I can't see any log in grafana.
I don't know where is wrong and how to figure it out.

**Comment by msyzzm** [comment]
After build NLog.Loki by myself, It works. I didn't change any code in repo.
Meybe something is wrong with nuget?

**Comment by corentinaltepe** [comment]
Hi @msyzzm,
sorry for my late reply.

I have been using this library for a while on Debian. But there could still be a regression. Could you enable [detailed NLog internal logs](https://github.com/NLog/NLog/wiki/Internal-Logging) to try and figure out why it doesn't work?

**Comment by msyzzm** [comment]
Hi, I test again and it works. Thank you.
